/* ============================================================================
 * 📈 機能カタログ（usage_catalog.gs）— 実装済み機能の全量リスト
 * ----------------------------------------------------------------------------
 * これが「分母」。機能利用ログ(usage.gs)が数える「分子」と突合して、
 *   一度も呼ばれていない機能＝死蔵 を洗い出す。分母が無いと「0回」を出せない。
 *
 * 中身は 2026-08-30 時点の実測で自動生成した365件:
 *   軍師API(GUNSHI_API_FNS) 168 ／ doPostアクション 172 ／ ポータル画面(tab) 25
 * ラベルはコード内コメントからの自動抽出＝短く言い直したいものが多い。
 *
 * ⚠️ラベルとカテゴリはシート「機能カタログ」で直せる（コード再デプロイ不要）。
 *   この配列は「シートが空のときの初期投入」と「シートに無いキーの補充」にだけ使う。
 * ⚠️新しい機能を作ってもここへの追記は不要＝ログに現れた未登録キーは自動でシートに追記される。
 *   ただし「作ったが一度も使われていない機能」はログに出ない＝ここに足さないと死蔵として検出できない。
 *   新機能を GUNSHI_API_FNS や handleApiRequest_ に足したら、ここにも1行足すこと。
 * ========================================================================== */

var USAGE_CATALOG_TAB_ = '機能カタログ';

// [システム, 機能キー, 機能名(日本語), カテゴリ]
var USAGE_INV_ = [
  ['軍師','addKioskReservation','端末キオスク用','予約'],
  ['軍師','addOrderDraftItem','当日の発注ドラフトに1件追加','在庫・発注'],
  ['軍師','addStockItem','','在庫・発注'],
  ['軍師','cancelKioskReservation','端末キオスク用','予約'],
  ['軍師','changeStockQty','賞味期限管理なしの品目の在庫数を増減','在庫・発注'],
  ['軍師','confirmOrderDelivered','黒服が現物を確認した発注を「納品済み」にする','在庫・発注'],
  ['軍師','deleteStockItem','','在庫・発注'],
  ['軍師','getCashCheckInit','dk','予約'],
  ['軍師','getCastRequestsToday','','付け回し'],
  ['軍師','getKioskCastNames','端末キオスク用','その他'],
  ['軍師','getKioskHall2','ホール','ホール・席'],
  ['軍師','getKioskReservations','includeCancelled=true で削除','予約'],
  ['軍師','getKioskShiftBoard','シフト一覧','スタッフ・シフト'],
  ['軍師','getKioskStaffList','軍師にログイン可能な名前一覧','スタッフ・シフト'],
  ['軍師','getKioskTsukemawashi','付け回し','付け回し'],
  ['軍師','getKioskWorkingCasts','実名','顧客'],
  ['軍師','getKioskCastKubun','当日の非通常キャストの区分マップ { 空白除去した実','その他'],
  ['軍師','getOpeningCheckInit','','予約'],
  ['軍師','getStockList','在庫発注マスタ一覧','在庫・発注'],
  ['軍師','getTodayPendingReservations','本日の未来店予約一覧','予約'],
  ['軍師','getUndeliveredOrders','承認済み・未納品の発注一覧','在庫・発注'],
  ['軍師','kioskApplyDelivery','確認後の在庫反映を一括適用','在庫・発注'],
  ['軍師','kioskAuthStart','','認証・設定'],
  ['軍師','kioskAuthStatus','','認証・設定'],
  ['軍師','kioskCancelOkuriEntry','送りを取消','送り'],
  ['軍師','kioskChangeTable','','ホール・席'],
  ['軍師','kioskCombineSeats','','ホール・席'],
  ['軍師','kioskDeleteDenpyo','伝票1行を削除','伝票・POS'],
  ['軍師','kioskDeleteDenpyoBulk','行番号は下','伝票・POS'],
  ['軍師','kioskAddDenpyo','sheetName は 領収書記録','伝票・POS'],
  ['軍師','kioskEndAtendouAtSeat','キオスク','ホール・席'],
  ['軍師','kioskExtendAtendouAtSeat','キオスク','ホール・席'],
  ['軍師','kioskGetCustomerDetail','顧客詳細','顧客'],
  ['軍師','kioskGetDenpyoDay','指定営業日の 日払い/領収書/納品 記録を返す','伝票・POS'],
  ['軍師','kioskGetOkuriBoard','当日の送りボード','送り'],
  ['軍師','kioskGetPendingDeliveries','在庫未反映の納品明細を伝票ごとに返す','在庫・発注'],
  ['軍師','kioskLogoutTs','端末が強制ログアウトTSをポーリング','認証・設定'],
  ['軍師','kioskRotateCast','','付け回し'],
  ['軍師','kioskSaveNextVisitMemo','次回対応メモの保存','予約'],
  ['軍師','kioskSaveOkuriEntry','送りを追加/更新','送り'],
  ['軍師','kioskSetGlobalOkuriMode','全体の送りモード切替','送り'],
  ['軍師','kioskSetHayaagari','','付け回し'],
  ['軍師','kioskSetInterval','','付け回し'],
  ['軍師','kioskSetOkuri','','送り'],
  ['軍師','kioskSetOkuriMode','','送り'],
  ['軍師','kioskSplitSeat','','ホール・席'],
  ['軍師','kioskUpdateDenpyo','伝票1行の指定列を修正','伝票・POS'],
  ['軍師','kioskVerifyPin','端末キオスク用','認証・設定'],
  ['軍師','registerStockPurchase','賞味期限管理品の購入登録','在庫・発注'],
  ['軍師','searchKioskCustomersV2','viewer','予約'],
  ['軍師','setCastRequestHandled','IEYAS軍師','付け回し'],
  ['軍師','setKioskReservationStatus','端末キオスク用','予約'],
  ['軍師','setSeatPlanCast','IEYAS軍師','ホール・席'],
  ['軍師','setupTableSession','既存予約への来店反映、または新規来店登録＋来店済み化','ホール・席'],
  ['軍師','submitCashCheck','payload','現金・締め'],
  ['軍師','submitOpeningCheck','黒服「開店の現金」提出','現金・締め'],
  ['軍師','submitSafeWithdrawal','黒服「金庫からの出金」記録','現金・締め'],
  ['軍師','updateKioskReservation','端末キオスク用','予約'],
  ['軍師','getKioskBootstrap','軍師フロント起動時の設定値','その他'],
  ['軍師','getKioskLoadAll','','その他'],
  ['軍師','addCustomer','顧客新規登録','顧客'],
  ['軍師','getKioskTasks','','その他'],
  ['軍師','completeKioskTask','タスク完了','その他'],
  ['軍師','applyFeeRenewalTicket','GUNSHI_API_FNS登録必須','その他'],
  ['軍師','getMemberRenewals','dueYm','顧客'],
  ['軍師','kioskUpdateCustomer','軍師から顧客情報を修正','顧客'],
  ['軍師','kioskDeleteDelivery','行ズレを防ぐため降順に削除する','在庫・発注'],
  ['軍師','kioskGetSouvenirStock','フロア別おみやげ在庫','在庫・発注'],
  ['軍師','kioskSetSouvenirStock','おみやげ在庫を絶対値でセット','在庫・発注'],
  ['軍師','kioskAdjustSouvenirStock','おみやげ在庫を増減','在庫・発注'],
  ['軍師','getSouvenirLog','おみやげ在庫の推移を返す','在庫・発注'],
  ['軍師','getServerTime','※ズレは端末側にしか現れないためサーバー単独では検知','認証・設定'],
  ['軍師','reportClockDrift','driftSec = 端末時刻 - サーバー時刻','認証・設定'],
  ['軍師','clearClockDrift','','認証・設定'],
  ['軍師','gunshiGetCastList','配信先の件数・名簿','その他'],
  ['軍師','gunshiBroadcastCast','メッセージを全キャストへ個別pushで一斉配信','通知・連絡'],
  ['軍師','kioskGetCustomerVisits','viewer','顧客'],
  ['軍師','gunshiBackfillVisits','commit=false でプレビュー','顧客'],
  ['軍師','gunshiImportTrustVisits','無ければソース=TRUSTで新規追加','顧客'],
  ['軍師','kioskSetGenji','','ホール・席'],
  ['軍師','kioskSetShusen','','ホール・席'],
  ['軍師','getOpeningPrepInit','開店前チェックの現状','現金・締め'],
  ['軍師','toggleOpeningPrep','開店前チェックの1項目×フロアをON/OFF','現金・締め'],
  ['軍師','getChecklistConfig','読み取りAPI','認証・設定'],
  ['軍師','getStocktakeTargets','棚卸し対象','在庫・発注'],
  ['軍師','submitStocktake','棚卸し実数を一括反映','在庫・発注'],
  ['軍師','syncMeishiRowsWithRoster','⚠️deleteRow は行番号がずれるので必ず下か','在庫・発注'],
  ['軍師','setMeishiLevel','感覚3段階をセットして判定','在庫・発注'],
  ['軍師','setStockSupplyStatus','現物が残っている酒を数えられなくなる','在庫・発注'],
  ['軍師','gunshiGetMenuLinks','','在庫・発注'],
  ['軍師','gunshiSetMenuLink','黒服が在庫→メニューの紐づけを確定する','在庫・発注'],
  ['軍師','gunshiGetBirthdays','黒服は個人userIdを持たない共有キオスク','顧客'],
  ['軍師','gunshiGetHandover','軍師','通知・連絡'],
  ['軍師','gunshiSaveHandover','軍師','通知・連絡'],
  ['軍師','getKeihiStaffNames','幽霊ロール','現金・締め'],
  ['軍師','kioskGetSlipImage','軍師','伝票・POS'],
  ['軍師','gunshiStartMendan','軍師','スタッフ・シフト'],
  ['軍師','gunshiGetMendanList','軍師','スタッフ・シフト'],
  ['軍師','gunshiJudgeMendan','judge = \'体験へ\' | \'面談で終わり\' |','スタッフ・シフト'],
  ['軍師','gunshiStartKurofukuMendan','軍師','スタッフ・シフト'],
  ['軍師','gunshiGetKurofukuMendanList','軍師','スタッフ・シフト'],
  ['軍師','gunshiJudgeKurofukuMendan','軍師','スタッフ・シフト'],
  ['軍師','gunshiGetGenjiShift','体験登録の前に、その源氏名が既にシフト表に入っている','ホール・席'],
  ['軍師','gunshiPunch','軍師のドリフト検知は12時間閾値','スタッフ・シフト'],
  ['軍師','gunshiPunchStatus','軍師の打刻カード用','スタッフ・シフト'],
  ['軍師','getKioskCustomerRoster','','顧客'],
  ['軍師','getReceiptReservationsToday','@708デプロイが本番専用機能を巻き戻した事故の復旧','予約'],
  ['軍師','logIssuedReceipt','','請求・領収'],
  ['軍師','getIssuedReceipts','軍師','請求・領収'],
  ['軍師','getReceiptPayees','','給与・売上'],
  ['軍師','getMonthlyPayReceipts','month省略時は最新の対象月','給与・売上'],
  ['軍師','getReceiptIssuers','軍師','請求・領収'],
  ['軍師','getOrderAlerts','shortage … 黒服が明示した 欠品・入荷未定','在庫・発注'],
  ['軍師','setOrderStatusManual','終売のときは連動して在庫を メニュー落ち にする','在庫・発注'],
  ['軍師','gunshiAwardData','voterName = 軍師のPIN確認済み LOG','評価・その他画面'],
  ['軍師','gunshiAwardVote','','評価・その他画面'],
  ['軍師','getWarCouncil','各ソースは個別 try/catch','評価・その他画面'],
  ['軍師','getSeikyuBootstrap','軍師','請求・領収'],
  ['軍師','saveSeikyusaki','軍師','請求・領収'],
  ['軍師','submitSeikyu','軍師','請求・領収'],
  ['軍師','kioskGetSeikyuImage','軍師／コンソール共通','請求・領収'],
  ['軍師','getSeikyuListKiosk','軍師','請求・領収'],
  ['軍師','getSeikyuGroupPhotos','軍師','請求・領収'],
  ['軍師','kioskGetGroupPhoto','軍師','その他'],
  ['軍師','getGunshiMaintenance','切替','認証・設定'],
  ['軍師','getPosMenu','','伝票・POS'],
  ['軍師','getPosBill','','伝票・POS'],
  ['軍師','posAddOrders','','伝票・POS'],
  ['軍師','posVoidOrder','','伝票・POS'],
  ['軍師','getPosOpenBills','','伝票・POS'],
  ['軍師','getPosMode','','伝票・POS'],
  ['軍師','setPosMode','モード切替','伝票・POS'],
  ['軍師','getPosBills','その営業日の伝票を全部返す','伝票・POS'],
  ['軍師','posSaveBill','伝票を保存','伝票・POS'],
  ['軍師','posCloseBill','会計する','伝票・POS'],
  ['軍師','posReopenBill','会計を取り消して伝票を編集できる状態に戻す','伝票・POS'],
  ['軍師','getPosClosed','その営業日の会計済み伝票行を返す','伝票・POS'],
  ['軍師','getPosDayStatus','','伝票・POS'],
  ['軍師','posDeleteBill','','伝票・POS'],
  ['軍師','getPosNextPay','','伝票・POS'],
  ['軍師','markSlipPrinted','','伝票・POS'],
  ['軍師','getSlipPrinted','','伝票・POS'],
  ['軍師','ccGateStatus','軍師','現金・締め'],
  ['軍師','deferKioskTask','タスクを「今日は持ち越す」と決める','その他'],
  ['軍師','undeferKioskTask','持ち越しを取り消す','その他'],
  ['軍師','getHibaraiUnknown','不明分の一覧','給与・売上'],
  ['軍師','hibaraiResolveUnknown','⚠️名寄せに登録する「受領書の表記」は、書き換え後の','給与・売上'],
  ['軍師','getClosingExtras','⚠️どれか1つが落ちても残りを返す','現金・締め'],
  ['軍師','resolveKaikeiCheck','会計伝票の要確認を1件「対応した」にする','伝票・POS'],
  ['軍師','ccRegisterPayee','','現金・締め'],
  ['軍師','getCashPendingDays','','現金・締め'],
  ['軍師','importTrustReportShot','⚠️実測で1枚あたり6〜12秒かかる','給与・売上'],
  ['軍師','clearTrustDayPay','永久に消せなくなる','給与・売上'],
  ['軍師','kioskGetCustomerNote','顧客1件の注意情報を読む','顧客'],
  ['軍師','kioskSaveCustomerNote','注意情報を保存','顧客'],
  ['軍師','gunshiNgCheckAssign','@param castName 付けようとしているキ','顧客'],
  ['軍師','gunshiNgBoard','店全体のNG盤面','顧客'],
  ['軍師','gunshiNgCheckReservation','@param memberId 会員番号 / cus','予約'],
  ['軍師','extractSeikyuSlipDate','⚠️関数名は据え置き','伝票・POS'],
  ['軍師','gunshiGetManual','軍師','評価・その他画面'],
  ['軍師','gunshiGetHakenRoster','today = 本日シフト表の派遣行に台帳のヒットを','スタッフ・シフト'],
  ['軍師','gunshiSaveHakenId','facePhoto, idPhoto, idPhot','スタッフ・シフト'],
  ['軍師','gunshiConfirmHaken','2回目以降','スタッフ・シフト'],
  ['軍師','gunshiGetHakenPhoto','台帳の写真を base64 で返す','スタッフ・シフト'],
  ['軍師','getNippo','','日報'],
  ['軍師','saveNippo','','日報'],
  ['軍師','confirmNippo','','日報'],
  ['軍師','reopenNippo','','日報'],
  ['ポータル/コンソール','gunshi','','その他'],
  ['ポータル/コンソール','kmendan','','スタッフ・シフト'],
  ['ポータル/コンソール','mendan','','スタッフ・シフト'],
  ['ポータル/コンソール','getCustomerBirthdays','','顧客'],
  ['ポータル/コンソール','adminGetHakenLedger','','顧客'],
  ['ポータル/コンソール','adminGetHakenPhoto','','顧客'],
  ['ポータル/コンソール','adminUpdateHakenRec','','スタッフ・シフト'],
  ['ポータル/コンソール','adminGetMendanList','','顧客'],
  ['ポータル/コンソール','adminDeleteMendan','','スタッフ・シフト'],
  ['ポータル/コンソール','seikyuData','','請求・領収'],
  ['ポータル/コンソール','seikyuGenerate','','請求・領収'],
  ['ポータル/コンソール','seikyuGenerateBundle','','請求・領収'],
  ['ポータル/コンソール','seikyuSetStatus','','請求・領収'],
  ['ポータル/コンソール','seikyuUpdate','','請求・領収'],
  ['ポータル/コンソール','seikyuSaveSettings','','顧客'],
  ['ポータル/コンソール','seikyuSaveSender','','請求・領収'],
  ['ポータル/コンソール','seikyuImage','','請求・領収'],
  ['ポータル/コンソール','issuerList','','その他'],
  ['ポータル/コンソール','issuerSave','','その他'],
  ['ポータル/コンソール','issuerDelete','','その他'],
  ['ポータル/コンソール','adminGetBills','','伝票・POS'],
  ['ポータル/コンソール','adminGetBillDetail','','伝票・POS'],
  ['ポータル/コンソール','adminGetAnnual','','顧客'],
  ['ポータル/コンソール','adminGetCustomerNote','','顧客'],
  ['ポータル/コンソール','adminSaveCustomerNote','','顧客'],
  ['ポータル/コンソール','adminGetCustomers','','顧客'],
  ['ポータル/コンソール','adminUpdateCustomer','','顧客'],
  ['ポータル/コンソール','adminAddCustomer','','顧客'],
  ['ポータル/コンソール','createNotice','','通知・連絡'],
  ['ポータル/コンソール','getNoticeReadMap','','通知・連絡'],
  ['ポータル/コンソール','repushNotice','','通知・連絡'],
  ['ポータル/コンソール','archiveNotice','','通知・連絡'],
  ['ポータル/コンソール','markNoticeRead','','通知・連絡'],
  ['ポータル/コンソール','getCastReservations','','予約'],
  ['ポータル/コンソール','adminGetTopBoard','','顧客'],
  ['ポータル/コンソール','getRsvMatrix','','予約'],
  ['ポータル/コンソール','setReservationCheckTime','','予約'],
  ['ポータル/コンソール','getReservationLog','','予約'],
  ['ポータル/コンソール','submitShift','','スタッフ・シフト'],
  ['ポータル/コンソール','declineNextWeek','','通知・連絡'],
  ['ポータル/コンソール','getShiftSubmitStatus','','スタッフ・シフト'],
  ['ポータル/コンソール','runShiftOpenNow','','スタッフ・シフト'],
  ['ポータル/コンソール','sendCastSeatRequest','','ホール・席'],
  ['ポータル/コンソール','cancelCastSeatRequest','','ホール・席'],
  ['ポータル/コンソール','castCall','','通知・連絡'],
  ['ポータル/コンソール','getCastSeats','','ホール・席'],
  ['ポータル/コンソール','sendPayrollReceipt','','給与・売上'],
  ['ポータル/コンソール','approveShift','','スタッフ・シフト'],
  ['ポータル/コンソール','notifyKurofukuShiftConfirmed','','スタッフ・シフト'],
  ['ポータル/コンソール','setStaffRole','','スタッフ・シフト'],
  ['ポータル/コンソール','setSafeAdminTag','','現金・締め'],
  ['ポータル/コンソール','setHakenStoreName','','スタッフ・シフト'],
  ['ポータル/コンソール','getNotifSettings','','顧客'],
  ['ポータル/コンソール','getChecklistConfig','','認証・設定'],
  ['ポータル/コンソール','saveChecklistConfig','','認証・設定'],
  ['ポータル/コンソール','saveNotifSettings','','顧客'],
  ['ポータル/コンソール','getResendableNotices','','通知・連絡'],
  ['ポータル/コンソール','resendNotices','','通知・連絡'],
  ['ポータル/コンソール','getCashThresholds','','現金・締め'],
  ['ポータル/コンソール','saveCashThresholds','','現金・締め'],
  ['ポータル/コンソール','getHolidays','','その他'],
  ['ポータル/コンソール','saveHolidays','','その他'],
  ['ポータル/コンソール','resetOpeningCheck','','現金・締め'],
  ['ポータル/コンソール','resetCashCheck','','現金・締め'],
  ['ポータル/コンソール','getCashCheckStatus','','現金・締め'],
  ['ポータル/コンソール','approveCashCheck','','現金・締め'],
  ['ポータル/コンソール','resetSafeWithdrawalLog','','現金・締め'],
  ['ポータル/コンソール','submitHairReceipt','','請求・領収'],
  ['ポータル/コンソール','setSalesDataDate','','その他'],
  ['ポータル/コンソール','resetGunshiSettings','','顧客'],
  ['ポータル/コンソール','resetGunshiSeating','','ホール・席'],
  ['ポータル/コンソール','syncRsrvWithReservations','','予約'],
  ['ポータル/コンソール','getOkuriMode','','送り'],
  ['ポータル/コンソール','getOkuriMeansStats','','送り'],
  ['ポータル/コンソール','kioskForceLogout','','認証・設定'],
  ['ポータル/コンソール','getKioskForceLogoutTs','','認証・設定'],
  ['ポータル/コンソール','getIeyasuRequests','','その他'],
  ['ポータル/コンソール','setIeyasuRequestStatus','','その他'],
  ['ポータル/コンソール','getHallLog','','ホール・席'],
  ['ポータル/コンソール','setHallJudge','','ホール・席'],
  ['ポータル/コンソール','getHallGroups','','ホール・席'],
  ['ポータル/コンソール','setHallGroups','','ホール・席'],
  ['ポータル/コンソール','kioskAuthConfirm','','認証・設定'],
  ['ポータル/コンソール','setOkuriMode','','送り'],
  ['ポータル/コンソール','getShiftRequests','','スタッフ・シフト'],
  ['ポータル/コンソール','kyukinStats','','評価・その他画面'],
  ['ポータル/コンソール','kintaiDay','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiMonth','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiSetPoint','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiRebuild','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiAllowance','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiFixPunch','','スタッフ・シフト'],
  ['ポータル/コンソール','kintaiRegister','','スタッフ・シフト'],
  ['ポータル/コンソール','getShiftMgmt','','スタッフ・シフト'],
  ['ポータル/コンソール','clearShiftRequests','','スタッフ・シフト'],
  ['ポータル/コンソール','getPublishStatus','','その他'],
  ['ポータル/コンソール','getSeatList','','ホール・席'],
  ['ポータル/コンソール','resetSeat','','ホール・席'],
  ['ポータル/コンソール','addKurofukuTask','','その他'],
  ['ポータル/コンソール','listKurofukuTasks','','その他'],
  ['ポータル/コンソール','deleteKurofukuTask','','その他'],
  ['ポータル/コンソール','addReservation','','予約'],
  ['ポータル/コンソール','updateReservation','','予約'],
  ['ポータル/コンソール','cancelReservation','','予約'],
  ['ポータル/コンソール','checkInReservation','','予約'],
  ['ポータル/コンソール','checkOutReservation','','予約'],
  ['ポータル/コンソール','setReservationStatus','','予約'],
  ['ポータル/コンソール','addYoyakuRequest','','予約'],
  ['ポータル/コンソール','doneYoyakuRequest','','予約'],
  ['ポータル/コンソール','deleteHairReceipt','','請求・領収'],
  ['ポータル/コンソール','publishPay','','給与・売上'],
  ['ポータル/コンソール','unpublishPay','','給与・売上'],
  ['ポータル/コンソール','publishRanking','','評価・その他画面'],
  ['ポータル/コンソール','unpublishRanking','','評価・その他画面'],
  ['ポータル/コンソール','importPayrollCsv','','給与・売上'],
  ['ポータル/コンソール','syncTrustAll','','給与・売上'],
  ['ポータル/コンソール','syncTrustDailyCash','','現金・締め'],
  ['ポータル/コンソール','syncTrustBills','','伝票・POS'],
  ['ポータル/コンソール','syncTrustBillItems','','伝票・POS'],
  ['ポータル/コンソール','getTrustSyncState','','給与・売上'],
  ['ポータル/コンソール','writeShiftCellPortal','','スタッフ・シフト'],
  ['ポータル/コンソール','addShiftStaff','','スタッフ・シフト'],
  ['ポータル/コンソール','castGetBirthday','','顧客'],
  ['ポータル/コンソール','castSetBirthday','','顧客'],
  ['ポータル/コンソール','castApplyBirthdayWeek','','顧客'],
  ['ポータル/コンソール','castCancelBirthdayWeek','','顧客'],
  ['ポータル/コンソール','adminApproveBirthdayWeek','','顧客'],
  ['ポータル/コンソール','adminSendbackBirthdayWeek','','顧客'],
  ['ポータル/コンソール','castGetProfile','','その他'],
  ['ポータル/コンソール','castSaveProfile','','その他'],
  ['ポータル/コンソール','getMenuBoard','','在庫・発注'],
  ['ポータル/コンソール','addMenuItem','','在庫・発注'],
  ['ポータル/コンソール','setMenuItemStatus','','在庫・発注'],
  ['ポータル/コンソール','setMenuItemLink','','在庫・発注'],
  ['ポータル/コンソール','deleteMenuItem','','在庫・発注'],
  ['ポータル/コンソール','suggestStockName','','在庫・発注'],
  ['ポータル/コンソール','setStockSupply','','在庫・発注'],
  ['ポータル/コンソール','previewMenuBulk','','在庫・発注'],
  ['ポータル/コンソール','importMenuBulk','','在庫・発注'],
  ['ポータル/コンソール','findDupStockNames','','在庫・発注'],
  ['ポータル/コンソール','mergeStockNames','','在庫・発注'],
  ['ポータル/コンソール','awardVote','','評価・その他画面'],
  ['ポータル/コンソール','awardAdminData','','評価・その他画面'],
  ['ポータル/コンソール','closeAwardMonth','','評価・その他画面'],
  ['ポータル/コンソール','awardSaveCategories','','評価・その他画面'],
  ['ポータル/コンソール','awardSetConfig','','評価・その他画面'],
  ['ポータル/コンソール','skillAdminData','','評価・その他画面'],
  ['ポータル/コンソール','skillSaveQuestion','','評価・その他画面'],
  ['ポータル/コンソール','skillDeleteQuestion','','評価・その他画面'],
  ['ポータル/コンソール','skillSaveGrade','','評価・その他画面'],
  ['ポータル/コンソール','skillSeedDefaults','','評価・その他画面'],
  ['ポータル/コンソール','skillImportDrafts','','評価・その他画面'],
  ['ポータル/コンソール','skillReviewNote','','顧客'],
  ['ポータル/コンソール','skillSetAnswer','','評価・その他画面'],
  ['ポータル/コンソール','skillSetStatus','','評価・その他画面'],
  ['ポータル/コンソール','skillFinalize','','評価・その他画面'],
  ['ポータル/コンソール','skillSetChapter','','評価・その他画面'],
  ['ポータル/コンソール','skillSeedAll','','評価・その他画面'],
  ['ポータル/コンソール','skillStart','','評価・その他画面'],
  ['ポータル/コンソール','skillSubmit','','評価・その他画面'],
  ['ポータル/コンソール','manualAdminData','','評価・その他画面'],
  ['ポータル/コンソール','manualSave','','評価・その他画面'],
  ['ポータル/コンソール','manualDelete','','評価・その他画面'],
  ['ポータル/コンソール','manualMove','','評価・その他画面'],
  ['ポータル/コンソール','manualMoveChapter','','評価・その他画面'],
  ['ポータル/コンソール','manualRenameChapter','','評価・その他画面'],
  ['ポータル/コンソール','manualSeedDefaults','','評価・その他画面'],
  ['ポータル/コンソール','manualResetDefaults','','評価・その他画面'],
  ['ポータル/コンソール','kassenPlay','','評価・その他画面'],
  ['ポータル/コンソール','kassenPing','','評価・その他画面'],
  ['ポータル/コンソール','kassenAdminData','','評価・その他画面'],
  ['ポータル/コンソール','kassenSetConfig','if','評価・その他画面'],
  ['ポータル','tab:home','handlePortalApi_ が','画面(ポータル)'],
  ['ポータル','tab:billbackfill','管理者向けの再投入は下の isAdmin &&','画面(ポータル)'],
  ['ポータル','tab:homelite','画面: homelite','画面(ポータル)'],
  ['ポータル','tab:homerest','画面: homerest','画面(ポータル)'],
  ['ポータル','tab:requests','画面: requests','画面(ポータル)'],
  ['ポータル','tab:awards','画面: awards','画面(ポータル)'],
  ['ポータル','tab:kassen','画面: kassen','画面(ポータル)'],
  ['ポータル','tab:yoyaku','画面: yoyaku','画面(ポータル)'],
  ['ポータル','tab:customers','画面: customers','画面(ポータル)'],
  ['ポータル','tab:customerVisits','画面: customerVisits','画面(ポータル)'],
  ['ポータル','tab:vacancy','画面: vacancy','画面(ポータル)'],
  ['ポータル','tab:yoyakuMonth','画面: yoyakuMonth','画面(ポータル)'],
  ['ポータル','tab:yoyakuCustomers','画面: yoyakuCustomers','画面(ポータル)'],
  ['ポータル','tab:shiftMgmt','画面: shiftMgmt','画面(ポータル)'],
  ['ポータル','tab:staffList','画面: staffList','画面(ポータル)'],
  ['ポータル','tab:billbackfillall','画面: billbackfillall','画面(ポータル)'],
  ['ポータル','tab:billbackfillstatus','画面: billbackfillstatus','画面(ポータル)'],
  ['ポータル','tab:ranking','画面: ranking','画面(ポータル)'],
  ['ポータル','tab:hair','画面: hair','画面(ポータル)'],
  ['ポータル','tab:skill','画面: skill','画面(ポータル)'],
  ['ポータル','tab:wine','画面: wine','画面(ポータル)'],
  ['ポータル','tab:bills','画面: bills','画面(ポータル)'],
  ['ポータル','tab:kyuritsu','画面: kyuritsu','画面(ポータル)'],
  ['ポータル','tab:billdetail','画面: billdetail','画面(ポータル)'],
  ['ポータル','tab:stats','画面: stats','画面(ポータル)'],];

/* シートを正本にする。無ければ作って USAGE_INV_ を全投入し、あればシートに無いキーだけ追記する。
   ⚠️既存行のラベル/カテゴリは絶対に上書きしない（人が直した内容を殺さない）。 */
function usageEnsureCatalog_() {
  var ss = getOrOpenSS_();
  var sh = ss.getSheetByName(USAGE_CATALOG_TAB_);
  if (!sh) {
    sh = ss.insertSheet(USAGE_CATALOG_TAB_);
    sh.appendRow(['システム', '機能キー', '機能名', 'カテゴリ', '備考']);
    sh.setFrozenRows(1);
    sh.getRange(2, 1, USAGE_INV_.length, 4).setValues(USAGE_INV_);
    return sh;
  }
  var have = {};
  var last = sh.getLastRow();
  if (last >= 2) sh.getRange(2, 1, last - 1, 2).getValues().forEach(function (r) { have[String(r[0]) + '|' + String(r[1])] = 1; });
  var add = USAGE_INV_.filter(function (r) { return !have[r[0] + '|' + r[1]]; });
  if (add.length) sh.getRange(sh.getLastRow() + 1, 1, add.length, 4).setValues(add);
  return sh;
}

/* カタログを {システム|キー: {label,cat}} で返す。 */
function usageCatalogMap_() {
  var sh = usageEnsureCatalog_();
  var last = sh.getLastRow();
  var map = {};
  if (last < 2) return map;
  sh.getRange(2, 1, last - 1, 4).getValues().forEach(function (r) {
    var sys = String(r[0] || ''), key = String(r[1] || '');
    if (!key) return;
    map[sys + '|' + key] = { sys: sys, key: key, label: String(r[2] || ''), cat: String(r[3] || 'その他') };
  });
  return map;
}

/* ログに現れたのにカタログに無いキーを追記する（新機能を作っても手入力が要らないように）。 */
function usageCatalogAppendUnknown_(pairs) {
  try {
    if (!pairs || !pairs.length) return;
    var sh = usageEnsureCatalog_();
    var rows = pairs.map(function (p) { return [p.sys, p.key, '', '未分類']; });
    sh.getRange(sh.getLastRow() + 1, 1, rows.length, 4).setValues(rows);
  } catch (_) { }
}
